/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param type 
 * @param summary 
 */


data class RequestModelB (

    @field:JsonProperty("type")
    val type: RequestModelB.Type,

    @field:JsonProperty("summary")
    val summary: kotlin.String

) : V1EndpointPostRequest {

    /**
     * 
     *
     * Values: value1,value2,value3
     */
    enum class Type(val value: kotlin.String) {
        @JsonProperty(value = "value1") value1("value1"),
        @JsonProperty(value = "value2") value2("value2"),
        @JsonProperty(value = "value3") value3("value3");
    }
}

