/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.RequestModelA
import org.openapitools.client.models.RequestModelB
import org.openapitools.client.models.RequestModelC

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 */


interface V1EndpointPostRequest {

}

